---
devices:
  samplerate: 44100
  chunksize: 2048
  silence_threshold: -60
  silence_timeout: 3.0
  capture:
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"
    format: S32LE
  playback:
    type: Alsa
    channels: 4
    device: "hw:D20,0"
    format: S32LE

filters:
  highpass:
    type: Conv
    parameters:
      type: File
      filename: /path/to/highpass.txt
  lowpass:
    type: Conv
    parameters:
      type: File
      filename: /path/to/lowpass.txt

mixers:
  to8:
    channels:
      in: 2
      out: 4
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 2
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 3
        sources:
          - channel: 1
            gain: 0
            inverted: false

pipeline:
  - type: Mixer
    name: to4
  - type: Filter
    channel: 0
    names:
      - lowpass 
  - type: Filter
    channel: 1
    names:
      - lowpass
  - type: Filter
    channel: 2
    names:
      - highpass 
  - type: Filter
    channel: 3
    names:
      - highpass 
   

